from __future__ import division
import sys, os, numpy, subprocess, multiprocessing, time, gc
import matplotlib.pyplot as plt
'''
Read files generated by bootstrap
'''
indir = 'outputs'
cutoffs = {}
for filename in os.listdir(indir):
    if 'cutoffs' not in filename:
        continue
    # open file and read content
    f = open(os.path.join(indir, filename), 'r')
    for line in f.readlines():
        line = line.strip().rstrip('\n')
        pieces = line.split(';')
        id_c = int(pieces[0])
        if id_c not in cutoffs:
            cutoffs[id_c] = []
        cutoffs[id_c].append(int(pieces[1]))
    f.close()

g = open(os.path.join(indir, 'consolidated.csv'), 'w')
program_codes = sorted(cutoffs.keys())
st = ';'.join(map(str,program_codes))
g.write(st + '\n')
for i in range(len(cutoffs[program_codes[0]])):
    aux = [cutoffs[c][i] for c in program_codes]
    st = ';'.join(map(str, aux))
    g.write(st + '\n')
g.close()

#
# plt.figure()
# plt.hist(cutoffs[11045], bins=50, alpha=0.75)
# plt.savefig('plots/distribution_cutoffs_11045.pdf')
# plt.show()

# id_c = 11045
#
# print numpy.average(cutoffs[id_c])
# print numpy.std(cutoffs[id_c])
#
# plt.figure()
# plt.hist(cutoffs[id_c], bins=50, alpha=0.75)
# plt.savefig('plots/distribution_cutoffs_'+str(id_c)+'.pdf')
# plt.show()
